### ISSUE TITLE
Question on sending input and listening to a process

### ISSUE THREAD

**Issue by dbsxdbsx** [tami5/process-stream#1]
What I want:
1. send some commands to a process;
2. listen to the feedback from the process(even I don't send command first);

For the 1st, Seems `stdin()` is the right method? Is there an example,
For the 2ed, the example using `next()` seems ok. But in my toy process:
```rust
fn main() {
    let mut rng = rand::thread_rng();
    // let v = vec!["ni", "hao", "san", "niu", "fdsfs"];
    let v = vec![1,2,3,4,5,6,7,8,9,10,11,12];

    loop {
        let mut input_str = String::new();
        io::stdin()
            .read_line(&mut input_str)
            .expect("get input failed");
        if input_str == "hi\r\n" {
            println!("got it");
        } else {
            let s = v.iter().choose_multiple(&mut rng, 1);
            println!("{}", s[0]);
        }
        sleep(Duration::from_secs(1));
    }
}
```
When using `next()` with it，even I didn't input anything, the process would keep output , which is not what I want. How to fix it?

**Comment by kkharji** [comment]
Not sure I get the example, but in recent commit you can do this

```rust
#[tokio::main]
async fn main() -> io::Result<()> {
    let mut process = Process::new("sort");

    // Set stdin (by default is set to null)
    process.stdin(Stdio::piped());

    // Get Stream;
    let mut stream = process.spawn_and_stream().unwrap();

    // Get writer from stdin;
    let mut writer = process.take_stdin().unwrap();

    // Spawn new async task and move stream to it
    let reader_thread = tokio::spawn(async move {
        while let Some(output) = stream.next().await {
            if output.is_exit() {
                println!("DONE")
            } else {
                println!("{output}")
            }
        }
    });

    // Spawn new async task and move writer to it
    let writer_thread = tokio::spawn(async move {
        writer.write(b"b\nc\na\n").await.unwrap();
        writer.write(b"f\ne\nd\n").await.unwrap();
    });

    // Wait till all threads finish
    writer_thread.await.unwrap();
    reader_thread.await.unwrap();

    // Result
    // a
    // b
    // c
    // d
    // e
    // f
    // DONE
    Ok(())
}

```

does this solve your issue?

**Comment by dbsxdbsx** [comment]
> Not sure I get the example, but in recent commit you can do this
> 
> ```rust
> #[tokio::main]
> async fn main() -> io::Result<()> {
>     let mut process = Process::new("sort");
> 
>     // Set stdin (by default is set to null)
>     process.stdin(Stdio::piped());
> 
>     // Get Stream;
>     let mut stream = process.spawn_and_stream().unwrap();
> 
>     // Get writer from stdin;
>     let mut writer = process.take_stdin().unwrap();
> 
>     // Spawn new async task and move stream to it
>     let reader_thread = tokio::spawn(async move {
>         while let Some(output) = stream.next().await {
>             if output.is_exit() {
>                 println!("DONE")
>             } else {
>                 println!("{output}")
>             }
>         }
>     });
> 
>     // Spawn new async task and move writer to it
>     let writer_thread = tokio::spawn(async move {
>         writer.write(b"b\nc\na\n").await.unwrap();
>         writer.write(b"f\ne\nd\n").await.unwrap();
>     });
> 
>     // Wait till all threads finish
>     writer_thread.await.unwrap();
>     reader_thread.await.unwrap();
> 
>     // Result
>     // a
>     // b
>     // c
>     // d
>     // e
>     // f
>     // DONE
>     Ok(())
> }
> ```
> 
> does this solve your issue?

Thanks reply. Now the input issue is solved. But the mechanism of `next()` is a little confusing. Because in my example, if no user input, then the process should have no output. 
But here within `process_stream`, it keeps outputting, why?

Meanwhile, I wonder if there is a way to wait response for a specific time after ` writer.write()`? For example, I want to inform user  "there is no response", if the process doesn't give feedback in 2 seconds.

**Comment by kkharji** [comment]
> But the mechanism of next() is a little confusing. 

indeed it kinda is. `next()` here is `StreamExt::next` this function would block the thread till either next returns some(output) or none.

There is another function `try_next` which would check without blocking if an output is send and not block otherwise. I believe that's what you are looking for in the example above, you can say for example while `within_threashold` (i.e. no more then 2 seconds) keep calling `try_next`, if no value then inform user there is no response

**Comment by dbsxdbsx** [comment]
> > But the mechanism of next() is a little confusing.
> 
> indeed it kinda is. `next()` here is `StreamExt::next` this function would block the thread till either next returns some(output) or none.
> 
> There is another function `try_next` which would check without blocking if an output is send and not block otherwise. I believe that's what you are looking for in the example above, you can say for example while `within_threashold` (i.e. no more then 2 seconds) keep calling `try_next`, if no value then inform user there is no response



For the `next()`, I think the blocking version is just ok in my case, since the `read_thread` is async, it would not block my whole thread. And I do need the stream inside `read_thread` to wait(block) for my next input.  My confusing is that, in my case (with the toy process I stated above) as long as the `write_thread` is launched with some input (any input), like this:
```rust
 let writer_thread = tokio::spawn(async move {
        let s = "hi";  // I write "hi" on purpose, since it would receive "got it" as a unique feedback
        writer.write(format!("{s}\r\n").as_bytes()).await.unwrap();
        writer
    });
```
**the steam inside the `read_thread` would then keep outputting "number" forever after receiving "got it" at first** --- this is what I don't understand, nothing with the block feature.

In addition, for the `try_next()`, to use it with `process_stream`, I think it essential to declare it like this firstly:
```rust
use process_stream::{Process, TryStreamExt};
```
then using it like this:
```rust
while let Some(output) = stream.try_next().await {
...
}
```
But the code can't be compiled, due to `trait bound` issue with `process_stream::Process`.

And for `within_threashold`, do you mean there is a method called `within_threashold` exactly? I didn't find it. And when googling this over rust, I found a [reference](https://stackoverflow.com/questions/65391496/is-there-a-way-to-make-streamextnext-non-blocking-fail-fast-if-the-stream-is).

**Comment by kkharji** [comment]
> For the next(), I think the blocking version is just ok in my case, since the read_thread is async, it would not block my whole thread. 

Yah exactly, just the async context.

> And I do need the stream inside read_thread to wait(block) for my next input.

Yes, you can get away with doing loop, and using try_next and writer.writer in same context.

> My confusing is that, in my case (with the toy process I stated above) as long as the write_thread is launched with some input (any input), the steam inside the read_thread would then keep outputting "number" forever after receiving "got it" at first --- this is what I don't understand, nothing with the block feature.

Not sure I get what you are trying to say here, but stream would keep streaming till the `stdout`/`stderr` is ended due to exit of any code (success or otherwise).

> In addition, for the try_next(), to use it with process_stream, I think it essential to declare it like this firstly:
> But the code can't be compiled, due to trait bound issue with process_stream::Process.

hmmm that's odd, let me write a test case for it and check out what the issue is, but fyi try_next return Result, so my first guess was Ok(Some()), but I'm getting errors ..

> And for within_threashold, do you mean there is a method called within_threashold exactly? I didn't find it. And when googling this over rust,

Oh, this is just a variable you set to that gets updated within the loop when the threshold passes, e.g.

```rust
let now = std::time::SystemTime::now();
while now.elapsed().unwrap().as_millis() < 2 {
    ...  keep trying to get input ...
}
```

**Comment by dbsxdbsx** [comment]
> Not sure I get what you are trying to say here, 

Ok, let me make it more clear.  I pasted the  toy process code again here:
```rust
fn main() {
    let mut rng = rand::thread_rng();
    let v = vec![1,2,3,4,5,6,7,8,9,10,11,12];

    loop {
        let mut input_str = String::new();
        io::stdin()
            .read_line(&mut input_str)
            .expect("get input failed");
        if input_str == "hi\r\n" {
            println!("got it");
        } else {
            let s = v.iter().choose_multiple(&mut rng, 1);
            println!("{}", s[0]);
        }
        sleep(Duration::from_secs(1));
    }
}
```
If inputing with `hi\r\n`, it outputs "got it"; if inputing with anything else, it would output a random number. **If no input, it would block(waiting for user's next input).**   And with control code like this:
```rust
use std::process::Stdio;

use process_stream::{Process, StreamExt};
use tokio::io::{self, AsyncWriteExt};

#[tokio::main]
async fn main() -> io::Result<()> {
    let p = r"toy process path";// replace it with your toy process path
    let mut process = Process::new(p);

    // Set stdin (by default is set to null)
    process.stdin(Stdio::piped());

    // Get Stream;
    let mut stream = process.spawn_and_stream().unwrap();

    // Get writer from stdin;
    let mut writer = process.take_stdin().unwrap();

    // Spawn new async task and move stream to it
    let reader_thread = tokio::spawn(async move {
        while let Some(output) = stream.next().await {
            if output.is_exit() {
                println!("DONE")
            } else {
                println!("{output}")
            }
        }
    });

    // Spawn new async task and move writer to it
    let writer_thread = tokio::spawn(async move {
        let s = "hi";
        writer.write(format!("{s}\r\n").as_bytes()).await.unwrap();
        writer
    });

    // Wait till all threads finish
    writer_thread.await.unwrap();
    reader_thread.await.unwrap();

    Ok(())
}

```
it would keep outputing random numbers after first print "got it", like these :
```
got it
8
9
5
10
6
8
```
**I think there should be no ouput after the 1st `got it`,** since  there is only one input called `hi\r\n`.

**Comment by kkharji** [comment]
> I think there should be no ouput after the 1st got it, since there is only one input called hi\r\n.

```rust
loop {
        let mut input_str = String::new();
        io::stdin()
            .read_line(&mut input_str)
            .expect("get input failed");
        if input_str == "hi\r\n" {
            println!("got it");
        } else {
            let s = v.iter().choose_multiple(&mut rng, 1);
            println!("{}", s[0]);
        }
        sleep(Duration::from_secs(1));
    }
}
```

Yah but the process can't what to output unless you create a stream over it, see 

https://github.com/xbase-lab/xclog/blob/2edaa8bf0abb1f95ea3c37e03db64dcc9cc114bd/src/logger.rs#L68

**Comment by dbsxdbsx** [comment]
> > I think there should be no ouput after the 1st got it, since there is only one input called hi\r\n.
> 
> ```rust
> loop {
>         let mut input_str = String::new();
>         io::stdin()
>             .read_line(&mut input_str)
>             .expect("get input failed");
>         if input_str == "hi\r\n" {
>             println!("got it");
>         } else {
>             let s = v.iter().choose_multiple(&mut rng, 1);
>             println!("{}", s[0]);
>         }
>         sleep(Duration::from_secs(1));
>     }
> }
> ```
> 
> Yah but the process can't what to output unless you create a stream over it, see
> 
> https://github.com/xbase-lab/xclog/blob/2edaa8bf0abb1f95ea3c37e03db64dcc9cc114bd/src/logger.rs#L68

I think it not the reason.
I changed the code like this:

```rust
let mut s = stream! {
          while let Some(output) = stream.next().await {
            if output.is_exit() {
               yield "done"
            } else {
                yield "output"
            }
        }
    }
    .boxed();

let reader_thread = tokio::spawn(async move {
        while let Some(value) = s.next().await {
            println!("got {}", value);
        }
    });
```
It would still keep outputting string.

And I think the real issue comes from `let mut writer = process.take_stdin().unwrap();`, because I found that my toy process kept receiving empty char, which triggers it to keep outputting.

**Comment by dbsxdbsx** [comment]
So far, though the behavior is out of my expectation when connecting to my toy process. But it behaviors correct when working with 3rd close sourced process.  That is, no matter how many commands are sent from ` writer.write`, the `read_thread`:
```rust
   let reader_thread = tokio::spawn(async move {
        loop {
            while let Some(output) = stream.next().await {
                if output.is_exit() {
                    println!("DONE")
                } else {
                    println!("{output}")
                }
            }
        }
    });
```
would not exit until receiving the last feedback.  

Then, in order to make the `reader_thread` lives longer enough, I change it into this:
```rust
 let reader_thread = tokio::spawn(async move {
 loop{
        while let Some(output) = stream.next().await {
            if output.is_exit() {
                println!("DONE")
            } else {
                println!("{output}")
            }
        }
        }
    });
```
I think it is time to close this issue since it has been lasted too long since posted.
