### ISSUE TITLE
Feature request: hide process window

### ISSUE THREAD

**Issue by dbsxdbsx** [tami5/process-stream#2]
When launching a process,  the process window would pop up. I hope it could be hidden, like [this](https://stackoverflow.com/questions/60750113/how-do-i-hide-the-console-window-for-a-process-started-with-stdprocesscomman).

**Comment by kkharji** [comment]
Could you test it @dbsxdbsx

**Comment by dbsxdbsx** [comment]
> Could you test it @dbsxdbsx

Thanks for your feedback. I have to apologize for the misleading error. Because I notice that this issue is not due to something with rust, but with dart--- I am using rust as FFI with flutter.  

That is, even with the older version (<= 0.4.1), there is no process window showing up, generally. And even with the latest version  (>= 0.4.2), the process window still shows up when using it with flutter. I finally fixed it by [this](https://stackoverflow.com/questions/67082272/dart-how-to-hide-cmd-when-using-process-run).
